//    -----------------------------------------------------------------------------
//      Copyright (C) Siemens AG 1998  All Rights Reserved.
//    -----------------------------------------------------------------------------
//
//     Project: NUMARIS/4
//        File: \n4_servers1\pkg\MrServers\MrImaging\seq\nc_2DFLASH\nc_2DFLASH_UI.h
//     Version: \main\9
//      Author: Clinical
//        Date: 2013-09-24 12:39:04 +02:00
//
//        Lang: C++
//
//
//
///  \file   a_nc_2DFLASH_UI.h
///  \brief  File containing declaraion of the UI class
///          - nc_2DFLASHUI
///
///  This file contains the implementation of the class nc_2DFLASHUI.
///  The sequence nc_2DFLASH use it to generate very nice images.
///
//     Remarks: This is the demo sequence nc_2DFLASH.
//              DO NOT base any diagnosis on images generated by this sequence.
///
//    -----------------------------------------------------------------------------

#ifndef nc_2DFLASH_UI_h
#define nc_2DFLASH_UI_h 1

//  -------------------------------------------------------------------------- *
//  Application includes                                                       *
//  -------------------------------------------------------------------------- *
#include "MrServers/MrImaging/seq/nc_2DFLASH/nc_2DFLASH.h"
#include "MrServers/MrProtSrv/MrProtocol/libUICtrl/UICtrl.h"

#ifdef WIN32
#include "MrServers/MrProtSrv/MrProtocol/libUILink/UILinkLimited.h"
#include "MrServers/MrProtSrv/MrProtocol/libUILink/UILinkSelection.h"
#endif

//  -------------------------------------------------------------------------- *
//  Forward declarations                                                       *
//  -------------------------------------------------------------------------- *
class MrProt;
class SeqLim;
class SeqExpo;
class Sequence;

namespace SEQ_NAMESPACE
{
    //  --------------------------------------------------------------------------
    //
    //  Name        : nc_2DFLASHUI
    //
    //  Description :
    /// \brief        This class basically is a storage for the pointers to the
    ///               original setValue / getValue / solve - handlers.
    ///
    ///               The sequence registers new UI handlers, which usually do
    ///               something, call the original UI handler, and then
    ///               do something else. To keep the information of the original
    ///               UI handlers, the nc_2DFLASHUI class stores the pointers.
    ///
    ///               It also provides the method registerUI to execute the
    ///               registration of all new handlers (and the storage of
    ///               the original pointers)
    ///
    //  --------------------------------------------------------------------------

    class nc_2DFLASHUI {

    public:

        //  --------------------------------------------------------------
        //
        //  Name        :  nc_2DFLASHUI::nc_2DFLASHUI
        //
        //  Description :
        /// \brief         Initialization of class members
        //
        //  Return      :
        //
        //  --------------------------------------------------------------
        nc_2DFLASHUI();

        //  --------------------------------------------------------------
        //
        //  Name        :  nc_2DFLASHUI::~nc_2DFLASHUI
        //
        //  Description :
        /// \brief         Destructor
        //
        //  Return      :
        //
        //  --------------------------------------------------------------
        virtual ~nc_2DFLASHUI();

        //  --------------------------------------------------------------------------
        //
        //  Name        : nc_2DFLASHUI::registerUI
        //
        //  Description :
        /// \brief        This function initializes the UI functions and
        ///               registers all given set / get / Solve - handlers
        ///
        ///               It can be executed on the measuement system, too, but is empty there.
        ///
        ///               On the host, it executes these steps:
        ///               - Declaration of pointers to UI classes
        ///               - Registration of overloaded set value handlers
        ///
        ///               It returns an NLS status
        ///
        NLS_STATUS registerUI (SeqLim &rSeqLim);

#ifdef WIN32

        //  --------------------------------------------------------------
        ///  \brief Helper class instances for UI handlers
        ///         - register new handler functions
        ///         - save pointer to original handler function
        ///         These classes execute only on the host.
        ///
        ///  The following line is an example which can be removed for
        ///  other sequences.
        //  --------------------------------------------------------------

        //UI_ELEMENT_LONG       m_Contrast;   // Example for set-handler
        //UI_ELEMENT_SELECTION  m_GradMode;   // Example for solve-handler

#endif  // end of ifdef WIN32
    };  // end of class nc_2DFLASHUI
};      // end of namespace SEQ_NAMESPACE

#endif  // end of ifndef nc_2DFLASH_UI_h

